---
title: 'Chapter 11: Univariate Regression'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(infer)
library(broom)
library(skimr)
library(gganimate)
library(tidyverse)

county <- read_rds("county.rds")
```


# Class One Start

### Scene 1

**Prompt:** Explore the county level data from [here](https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/) with your partner and try to figure out the variables mean. Can you find any "interesting" observations? Which variables are worth looking at? `poverty` is the percentage of the county living in poverty is 2018. `less_than_hs` is the percentage of the county without at least a high school diploma. `hs` is the percent of the county who have a high school degree, but no further education.



# Scene 2

**Prompt** Let’s start by exploring our numerical outcome variable `poverty` and our numerical explanatory variable `less_than_hs`. What is the average poverty rate in the US? How does this compare with that of your county (if not from US look up Middlesex County - the county that Cambridge, MA is in)? Furthermore, what is the average percentage of adults without and with a high school diploma? Which state's county has the highest percentage of adults without a high school diploma?


# Scene 3

**Prompt** What is the correlation coefficient of `poverty` and `less_than_hs`? What does it mean?


# Scene 4

**Prompt** Use a scatterplot to visualize this data, including a straight line of best fit.


# Scene 5

**Prompt** Create an animation of the scatterplot above with the percent of adults with less than a high school diploma on the x axis and the poverty rate in the y axis. This scatterplot should transition through the four US regions. Hint: classify the 'county' data into the 4 US regions. Then create an animation of a scatterplot that transitions through each region. Hint: Read the [Animation appendix](https://davidkane9.github.io/PPBDS/C-animation.html) of the *[Primer](https://davidkane9.github.io/PPBDS/)*. You only need to add one command to the basic static `ggplot()` call.


# Scene 6

**Prompt** Using the `lm()` function, fit a model with this data in which `poverty` is the dependent variable and `less_than_hs` is the independent variable. Save the resulting object as `poverty_model`. Then, use the tidy() function found in section 11.1.2 to obtain the regression parameters. You should have a 2x7 regression table with terms of (Intercept) and `less_than_hs`, as well as an estimate, std.error, statistic, p.value, conf.low, and conf.high. Write one sentence explaining what the intercept means and one sentence about what the slope means.


# Scene 7

**Prompt** Use nest() to create a bootstrap sample of the linear regression. In this dataset, we'll have a resampled collection of counties in which we’ll sometimes have multiple counties represented and sometimes there won’t be any from our original 'county' data.


# Scene 8 

**Prompt**  Now, using the starter code above, go ahead and add more columns. Make one called `mod` which will contains the model objects created by `lm()`. Then, add one called `reg_results` which will tidy the objects created by `lm()`, and then one called `disp_coef` which will display the regression coefficient for each bootstrap sample. 


# Scene 9 

**Prompt** Create a confidence interval of the slope of our linear regression. What is the value at the 50th percentile? Is that expected? Provide a Bayesian and Frequentist interpretation of this interval.


# Scene 10 

**Prompt** Now, let's use a shortcut. Use the confidence intervals reported by `lm()` and `tidy()`.

# Scene 11

**Prompt** Alas, our data is missing Travis County in Texas. Suppose Travis County has 10.9% of adults with less than a high school degree. What do you think its poverty rate would be? Why? 

# Scene 12

**Prompt** Suppose I tell you now that Travis County has a 12% poverty rate. By how much was your estimate off? Why?

# Scene 13

**Prompt** Now, compute the fitted and residual values for each county. Explain what the following columns mean in one sentence each: poverty, pct_less_hs, .fitted, .resid. What does it mean to have a positive residual?


# Scene 14

**Prompt** Find the largest positive residual and largest negative residual. Why do you think there is such a large discrepancy?


# Scene 15

**Prompt** Go back and read the first part of Chapter 11 in the *Primer*. Are we modeling for explanation or for prediction? How do you know?


# Challenge Problems

# Scene 1

**Prompt** Find the standard error of the fitted values, and then construct a confidence interval. Remember, a 95% confidence interval can be found by adding/subtracting 1.96 * SE to the mean. Why is the uncertainty for particular predictions higher than the uncertainty for our estimate of the coefficient on less_than_hs?


# Scene 2

**Prompt** Take a look at the babynames library. Replicate the animation below exactly!


